### ISSUE TITLE
Read-only data should be passed to a kernel as const

### ISSUE THREAD

**Issue by kynan** [OP2/PyOP2#114]
A kernel argument with access descriptor `op2.READ` should be passed to a kernel as `double const *`. In the kernel signature such arguments should therefore also be declared as `const`.

Doing this currently fails since the generated wrapper code passes in a non-const pointer. Note that passing in a `double const *` in the wrapper code when the kernel declares the argument as `double *` will still work, since passing a `const` pointer to a non-const argument is legal, but not the other way round.

**Comment by wence-** [comment]
This is going away due to codegen rewrite.
