### ISSUE TITLE
Efficiently evaluate complex Dat expressions / linear combinations

### ISSUE THREAD

**Issue by kynan** [OP2/PyOP2#140]
An expression such as

```
a = op2.Dat(...)
b = op2.Dat(...)
c = op2.Dat(...)
d = (a + 2*b + c)/3
```

should ideally be evaluated without the need for creating temporaries in the process (c.f. expression templates in C++).

[numexpr](https://code.google.com/p/numexpr/) might be worth a look.

**Comment by connorjward** [comment]
This is supported in pyop3.

**Comment by FabioLuporini** [comment]
omg, 11 years ago 😬
