### ISSUE TITLE
Cap lazy evaluation trace length

### ISSUE THREAD

**Issue by wence-** [OP2/PyOP2#440]
The current default is for an unbounded lazy evaluation trace length.  While on the one hand we might argue that if the user doesn't look at any data for so long that this becomes a problem, they have a bug, it sort of looks bad from our side (because it seems like we're leaking memory).

I would argue for changing the default  for "lazy_max_trace_length" from "0" (meaning unbounded) to (say) 100.  Which should be big enough to allow loop fusion opportunities but not so large that things get out of hand.

**Comment by kynan** [comment]
Implemented in #441
