### ISSUE TITLE
petsc4py pip dependency spuriously not satisfied

### ISSUE THREAD

**Issue by dham** [OP2/PyOP2#453]
While installing PyOP2 on a clean MacBook, petsc4py complained that our petsc version did not satisfy the version requirements for petsc4py. You won't notice this on an upgrade because of the --no-deps argument. Should we just add --no-deps to the install instructions (since previous lines in the install instructions cause the user to install all the dependencies anyway)?

**Comment by kynan** [comment]
Suppose that would be an option. The alternative is to export `$PETSC_DIR`, which causes petsc4py to skip the check.

**Comment by wence-** [comment]
Option two is a bad idea, since pip installing petsc doesn't tell you what PETSC_DIR is.

**Comment by kynan** [comment]
Agreed, it only makes sense if you build/install PETSc from source rather than via pip.

**Comment by wence-** [comment]
Closing, due to install-script methodology.
