### ISSUE TITLE
Using C++ libraries from generated code

### ISSUE THREAD

**Issue by miklos1** [OP2/PyOP2#461]
This is about code generation for point evaluation and libspatialindex being a C++ library.

I used pyop2.compilation.load to compile and load the code which was generated on the fly, and it worked fine until I added libspatialindex. libspatialindex is, unfortunately, written in C++. While it seems to have a C API, I'm not sure if that works the way I want to use it (https://github.com/libspatialindex/libspatialindex/issues/76); mailing list archives suggest that its C API was added to make it easier to create a Python interface.

pyop2.compilation.load expects and 'extension' argument, the docstring suggesting that this should be either "c" or "cpp", however it's kinda irrelevant, as we always use the C compiler and the C linker. Since I can separate the libspatialindex interfacing C++ code from the generated C code, I can precompile the former into an object file and have it added to ldargs. That way using the C compiler suffices. However, I still need to use a C++ linker because of the precompiled C++ object file, which I currently cannot do in PyOP2. I could make this change to PyOP2, but I wonder if there is a better way to tackle the high-level problem.

**Comment by FabioLuporini** [comment]
I *think* that if the extension is cpp, the compiler/linker automatically switch to C++. I'm compiling and running C++ code with loop fusion.

**Comment by miklos1** [comment]
This issue might be invalid, as my thing somehow used to work for the last few days when I was working on it.
