### ISSUE TITLE
Slightly overzealous check in petsc_base.py?

### ISSUE THREAD

**Issue by dorugeber** [OP2/PyOP2#463]
```
    def values(self):
        base._trace.evaluate(set([self]), set())
        self._assemble()
        if self.nrows * self.ncols > 1000000:
            raise ValueError("Printing dense matrix with more than 1 million entries not allowed.\n"
                             "Are you sure you wanted to do this?")
        return self.handle[:, :]
```

Is this here to stop `M.values` from being used, or is it only supposed to stop people from printing to screen?

If the former, this stops me from using NumPy to do an SVD, say, or is there another way I should be doing this?

```
In [1]: mat = assemble(a).M.values

In [2]: import numpy as np

In [3]: np.linalg.svd(mat)[1]
Out[3]: 
array([ 0.12485408,  0.12386951,  0.12355023, ...,  0.00026754,
        0.00026754,  0.00025435])
```

**Comment by wence-** [comment]
So I picked a largish size, but maybe it's a bit small.  Do you need the full SVD, if not, I recommend using SLEPc:

```python
from slepc4py import SLEPc

svd = SLEPc.SVD().create()

svd.setOperator(A.M.handle)
svd.setFromOptions()
svd.solve()
nconv = svd.getConverged()
u, v = mat.createVecs()

for i in range(nconv):
     s = svd.getSingularTriplet(i, u, v)
     print "Singular value", s
     print "Left vector"
     u.view()
     print "Right vector"
     v.view()
```

**Comment by dorugeber** [comment]
What do you mean by "Do you need the full SVD"?  Typically I'd be doing this if I suspected my matrix was singular, so I wouldn't want (just) the 10 *largest* singular values, say.

**Comment by wence-** [comment]
So my rationale for putting a cap in was that occasionally, people (*cough* Christian) would ask for the dense matrix for massive matrices and petsc would barf in bad ways.  There are a few options available:

1. Up the limit
2. Add option to say "I know what I'm doing, ignore the limit"
3. Just bypass the values accessor:

You can always get at the values doing:

```python
vals = A.M.handle[:, :]
```

**Comment by dorugeber** [comment]
I'm happy with 3.

**Comment by wence-** [comment]
I will close this then.
