### ISSUE TITLE
Creating an OP2 Kernel with more than 1 FunDecl in AST

### ISSUE THREAD

**Issue by thomasgibson** [OP2/PyOP2#501]
Hello,

I noticed a few changes to PyOP2 since I last used it. In particular, in `base.py`, line 3781, there is an assertion:
`asset len(fundecls) == 1, "Illegal Kernel"`

This is a problem for the specialized SLATE form compiler, as the AST I provide has more than a single FunDecl object: The body of the kernel has a macro function, and several sub-functions provided by TSFC for evaluating integral forms. As a result, I'm no longer able to produce the kernels I need. Since the changes.

My question is: Is there a particular reason for the assertion? And in particular, is there a way around this?

Thank you for any assistance!

**Comment by thomasgibson** [comment]
A potential fix for this can be found in the branch [multiple-fundecls](https://github.com/OP2/PyOP2/tree/multiple-fundecls)

**Comment by miklos1** [comment]
I think you should file your branch as a pull request where we can properly discuss and comment on it.

**Comment by thomasgibson** [comment]
Okay will do.
