### ISSUE TITLE
Ill-defined equality predicates

### ISSUE THREAD

**Issue by miklos1** [OP2/PyOP2#510]
Various classes representing OP2 data structures have custom `__eq__` and `__ne__` methods, but no custom `__hash__`. That basically means that "`a == b` implies `hash(a) == hash(b)`" does not hold. Some code generation relies on the very discriminating default hash function (which corresponds to object equality as equality predicate), while the API tests check for the presence of a less discriminating `==` and `!=`.

**Comment by connorjward** [comment]
Moved to pyop3 https://github.com/connorjward/pyop3/issues/37
