### ISSUE TITLE
Install instructions don't result in a complete build

### ISSUE THREAD

**Issue by nickaj** [OP2/PyOP2#522]
Following the install instructions, you end up with petsc3.8.0.dev0 and are unable to install petsc4py which requires petsc <3.7, >=3.6

**Comment by wence-** [comment]
This is, somehow, I think, a bug in petsc4py requirements for the non-released version.  I think it works if you do `pip install petsc4py --no-deps`.

**Comment by connorjward** [comment]
Closing as install issue is very old.
