### ISSUE TITLE
Unrolled wrapper code is quite unhealthy for high-order kernels

### ISSUE THREAD

**Issue by miklos1** [OP2/PyOP2#537]
In most cases, PyOP2 generates unrolled loops in the wrapper. With high-order elements, that generates a lot of code, and GCC fails to de-unroll them, so it becomes a lot of code binary as well.

This also makes the C compilation times minutes instead of seconds.

**Comment by wence-** [comment]
I recommend that @tj-sun changes this as part of his packing changes.
