### ISSUE TITLE
Similar package and citation

### ISSUE THREAD

**Issue by gpkc** [OP2/PyOP2#542]
I started developing an very similar package (https://github.com/padmec-reservoir/elliptic), however only now I found this one. The namings are very similar (kernels, etc) and the concept of computing on unstructured meshes is quite the same.

There are, however, some differences. ELLIPTIc builds its kernels using a vectorized API rather than C-like kernels. Also, we intend to allow for hanging-nodes (non-manifold meshes) and adaptation.

That said, I want to cite your package on my thesis and papers. Are there any publications I can use?

**Comment by gpkc** [comment]
Great, thanks. I see that Firedrake uses Finite Elements. Do you know if someone is using PyOP2 with Finite Volumes?

**Comment by wence-** [comment]
I'm not aware of anyone using pyop2 for finite volume stuff.  However, OP2 (which is quite related) has been used extensively for finite volume discretisations of flow problems.  See the papers listed here: http://www.oerc.ox.ac.uk/projects/op2

**Comment by gpkc** [comment]
OK, thanks for all the info. You may close the issue if you wish!
