### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by gpkc** [OP2/PyOP2#543]
Is Python 3 currently fully supported? I saw some commits that seemed to add support for it, but the readme states that python2 is a requirement.

**Comment by miklos1** [comment]
Only Python 3 is supported. README must be outdated.

**Comment by dorugeber** [comment]
@miklos1 I think it's required to install PETSc?

**Comment by miklos1** [comment]
Yes, so it is an install dependency. But PyOP2 will not work with Python 2.

**Comment by gpkc** [comment]
@miklos1 Okay, thanks.
