### ISSUE TITLE
setup.py not installing codegen

### ISSUE THREAD

**Issue by JaroslavHron** [OP2/PyOP2#566]
doing direct installation into prefix directory 
`python3 -s setup.py --no-user-cfg install --prefix=/usr/local/pkg/pyop2`
will not install the `codegen` subpackage

it has to be explicitly listed as
```
setup( ..., packages=['pyop2','pyop2.codegen'], ....)
```
or with `setuptools` you coud use `find_packages()`
```
from setuptools import setup, find_packages

setup( ..., packages=find_packages(), ....)
```

**Comment by wence-** [comment]
Merged your pr. thanks.
