### ISSUE TITLE
Exception raised while handling mismatched kernels

### ISSUE THREAD

**Issue by angus-g** [OP2/PyOP2#576]
In `pyop2.compilation.Compiler.get_so`, there's a check that all ranks on the involved communicator are running the same kernel (by a collective reduce over a hash of the code). The intention is that if this fails, the rank 0 processor should create a directory to hold the different mismatched kernel source, and every processor writes a file into this directory. However, due to the way the collective operation works, a processor may not think it has an incorrect kernel (the check is at https://github.com/OP2/PyOP2/blob/master/pyop2/compilation.py#L258). In particular, if rank 0 believes its hash matches, it doesn't create the output directory, and exceptions are raised on all other ranks because that directory doesn't exist.

The following code reproduces in the 2-processor case for me:
```python
from firedrake import *
from mpi4py import MPI
import numpy as np

mesh = BoxMesh(10, 10, 10, 1, 2, 3, reorder=True)
V = VectorFunctionSpace(mesh, "CG", 2)
Q = FunctionSpace(mesh, "CG", 2)

X = SpatialCoordinate(mesh)
T = Function(Q, name="Temp")

if MPI.COMM_WORLD.Get_rank() == 0:
    a = 1
else:
    a = 2

T.interpolate(0.5 + 0.1*cos(np.pi * X[0] / a))
```

The end of the backtrace confirming that this is due to the directory not existing, raised on the rank 1 processor
```
...
[1,1]<stderr>:  File "/scratch/xd2/rad552/Firedrake/firedrake/src/PyOP2/pyop2/compilation.py", line 265, in get_so
[1,1]<stderr>:    with open(srcfile, "w") as f:
[1,1]<stderr>:FileNotFoundError: [Errno 2] No such file or directory: '/scratch/g40/ahg157/tmp/pyop2/0f/mismatching-kernels/src-rank1.c'
```

**Comment by wence-** [comment]
Can you confirm that #577 fixes the problem for you? It worked for me for your test case.

Thanks for the report!
