### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by wence-** [OP2/PyOP2#58]
Python 2.7 was the final major release of the python 2 series.  Bugfixes continue to be applied but no new functionality appears.

It should not be too difficult to update PyOP2 to be python3 compatible.  (2to3.py can do most of it).  The only real issue I see is that ubuntu doesn't currently ship a cython version compatible with python3.

**Comment by miklos1** [comment]
This is plausibly fixed in #511. Although PyOP2 is not tested through Firedrake against Python 3, because Firedrake does not Python 3 yet, but PyOP2 is tested with its own test suite against Python 3.
