### ISSUE TITLE
Add IdentityMap object

### ISSUE THREAD

**Issue by ReubenHill** [OP2/PyOP2#592]
PyOP2 has an implicit Identity map which would ideally be implemented for the `cell_node_map` of a DGPO function space on a `VertexOnlyMesh`.

To use this it you have to set the `map` argument to `None` when creating a PyOP2 `Arg`:
```
class Arg(object):
    ...
    def __init__(self, data=None, map=None, access=None, lgmaps=None, unroll_map=False):
        ...
        :param map:  A :class:`Map` to access this :class:`Arg` or the default
                     if the identity map is to be used.
```
We should create an explicit `IdentityMap` object that takes an iterset and a toset, but has no values. This can them be returned as, for example, the `cell_node_map` of a DGPO function space on a `VertexOnlyMesh`.

**Comment by connorjward** [comment]
Moved to pyop3 https://github.com/connorjward/pyop3/issues/34
