### ISSUE TITLE
CI doesn't test merge commits to master any more

### ISSUE THREAD

**Issue by wence-** [OP2/PyOP2#607]
Since #604, we test the merge commit in the PR, but don't actually test the final merge. Since our merges are not always fast-forwards, this might result in missed breakages.

I think we should also build-test on the push to trunk, which I guess is a case of changing the `on` specifier in ci.yml to be the union of the pull_request and push+master things.

@connorjward is this easy to do?

**Comment by connorjward** [comment]
Yep should be straightforward. On it.
