### ISSUE TITLE
Understanding the dim attribute

### ISSUE THREAD

**Issue by connorjward** [OP2/PyOP2#633]
AIUI the `dim` for some data structure should correspond to its dimension. For example `[1, 2, 3] -> 1`, `[[1, 2], [3, 4]] -> 2` etc. However in PyOP2 for some reason we report `dim` as a tuple instead of an integer. This makes sense for mixed things but not for single dats for example.

I am also getting quite confused by the usage of `shape` and `dim`. They seem to be quite interchangeable which doesn't seem right. The most obvious example of this I can find is [here](https://github.com/OP2/PyOP2/blob/master/pyop2/base.py#L1688):

```python
def _check_shape(self, other):
        if other.dataset.dim != self.dataset.dim:
            raise ValueError('Mismatched shapes in operands %s and %s',
                              self.dataset.dim, other.dataset.dim)
```

**Comment by wence-** [comment]
`dim` is the shape at each node of a `dataset`. the `shape` properties are generally the shape of the global data associated (if that property exists). So:

```python

s = Set(10)
d = DataSet(s, (3, 4, 2))
d2 = DataSet(s, (4,))
md = MixedDataSet(d, d2)

dat = Dat(d)
dat2 = Dat(d2)

d.dim == (3, 4, 2)
d2.dim == (4,)
md.dim = ((3, 4, 2), (4,))
d.data.shape == (10, 3, 4, 2)
```

This could/should be tidied up.

**Comment by connorjward** [comment]
That's very clear thanks. I ran into this confusion trying to get `Args` to not carry an explicit length (i.e. `shape[0]`). Looks like `dim` is exactly what I'm looking for.

I'll add this to the list of things that need tidying.
