### ISSUE TITLE
-DPYOP2_PROFILING 

### ISSUE THREAD

**Issue by sv2518** [OP2/PyOP2#648]
We could wrap the log events in the C kernels in preprocessor macros so they are conditionally included.
```
#ifdef PYOP2_PROFILING
PetscClassIdRegister(...);
...
#endif
```
 In order to implement it you would need to pass -DPYOP2_PROFILING as an argument to the compiler.

**Comment by connorjward** [comment]
I was thinking some more about this and realised that's it's not necessary since we generate the C code at runtime. We could simply do something like:
```py
func_header = "void wrap_kernel_..."
profiling_code = """
    PetscClassIdRegister(...)
    ...
"""
func_body = "..."

if configuration["profiling_enabled"]:
    source = func_header + profiling_code + func_body
else:
    source = func_header + func_body
```

**Comment by connorjward** [comment]
Closing as this change is not necessary. As an aside, I have added some utility methods in https://github.com/connorjward/pyop3 that make this sort of addition straightforward.
