### ISSUE TITLE
Deprecation warning for distutils Version classes.

### ISSUE THREAD

**Issue by mjg41** [OP2/PyOP2#651]
Deprecation warning from PyOP2 from distutils in:
https://github.com/OP2/PyOP2/blob/master/pyop2/compilation.py

DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.

**Comment by JDBetteridge** [comment]
Hmmm, `distutils` is [going away soon](https://www.python.org/dev/peps/pep-0632), we should probably try and remove all references to it in PyOP2

I've started work in a branch [here]() which should fix that issue. There are more references to `distutils` elsewhere that need removing.

Let me know if this solves your issue
