### ISSUE TITLE
Flops profiling per local kernel

### ISSUE THREAD

**Issue by sv2518** [OP2/PyOP2#669]
In the PR https://github.com/OP2/PyOP2/pull/668 I fixed the flop counting for our kernels. The FLOPS are counted per local kernel and then scaled up by the outer loops over the elements of the mesh. In the end, we only log the FLOPS for the global kernel.

It would be nice if we could log the numbers per local kernel so that someone (like me :)) who wants the FLOPS of a local kernel can just access them by reading the corresponding column in the summary that is printed when you pass in `-log_view`.

I don't have the time to work out how to do this correctly, I think we need to be careful that we don't accidentally add the FLOPS of the local kernels to the count for the global kernels in the logging process.

I will work around this for now by dumping the flops for my slate kernels in a file see https://github.com/OP2/PyOP2/tree/sv/dump-slate-flops

**Comment by connorjward** [comment]
Closing as moved to pyop3 https://github.com/connorjward/pyop3/issues/35
