### ISSUE TITLE
Expunge `PYOP2_NO_FORK_AVAILABLE`

### ISSUE THREAD

**Issue by connorjward** [OP2/PyOP2#684]
See [discussion](https://github.com/firedrakeproject/firedrake/wiki/Firedrake-meeting-2022-11-23#jb-pyop2-pyop2_no_fork_available-status).

**Comment by inducer** [comment]
I still maintain it, just in case. As for use, the story is a bit complex. With OpenCL, the JIT is mostly in-process, however https://github.com/pocl/pocl/ does fork a linker AFAIK. None of this appears to have been a source of problems so far on Lassen (a DOE machine) that we run things on.

As for Loopy, if you use it to do the JIT'ing, you'll be using `codepy`, which internally already calls into `pytools.prefork`.

**Comment by connorjward** [comment]
Closing as this has been moved to Firedrake https://github.com/firedrakeproject/firedrake/issues/3820
