### ISSUE TITLE
Add LRU cache

### ISSUE THREAD

**Issue by connorjward** [OP2/PyOP2#696]
We should introduce an LRU cache object/function to prevent unbounded memory usage by our in-memory caches. We will need to be careful about including the communicator in the cache key somehow so we never evict items from some ranks but not others.

Related issue #693.
Related discussion https://github.com/firedrakeproject/firedrake/discussions/2865

**Comment by wence-** [comment]
Reminder, that `functools.lru_cache` exists

**Comment by connorjward** [comment]
It does. But I think we need to be careful about communicators. I think that we need basically to have an LRU cache per communicator. Otherwise eviction won't be collective.

**Comment by wence-** [comment]
Natural thing to do is to hook the cache on the communicator as an MPI attribute then.

**Comment by connorjward** [comment]
Good suggestion, thanks! I still need to decide on the right API. I would quite like to implement this in tandem with my idea for a "cache manager" (https://github.com/OP2/PyOP2/issues/693).

**Comment by wence-** [comment]
> Good suggestion, thanks!

Remember to do so on the inner "PyOP2" comm.

**Comment by connorjward** [comment]
Closing as solved by https://github.com/OP2/PyOP2/pull/724
