### ISSUE TITLE
`__del__` based teardowns should be replaced by weakref finalizers

### ISSUE THREAD

**Issue by wence-** [OP2/PyOP2#702]
`__del__` is explicitly marked as "not a destructor" in the python docs. The closest you can get to C++-style RAII semantics is by setting up weakref finalizers that tear things down when the object goes out of scope.

The one caveat here is that you can't set up a ref-cycle between the arguments to the finalizer and the object you're attaching it to. This is normally fine because there's usually only a one-way reference between the two (though you probably have to be a bit careful stashing objects inside communicators).

Concretely, code like this:

https://github.com/OP2/PyOP2/blob/edae288420cb68d1f613b9e377c38629753223a7/pyop2/types/dat.py#LL91C1-L93C34

Is better off, doing (in `__init__`):

```python
import weakref

...
def __init__(self, comm):
    self.comm = mpi.internal_comm(comm)
    weakref.finalize(self, mpi.decref, self.comm)
```

Similarly, the `temp_internal_comm` context manager:

https://github.com/OP2/PyOP2/blob/edae288420cb68d1f613b9e377c38629753223a7/pyop2/mpi.py#L251-L272

Should not decref the internal comm in a custom `__del__` method, but rather not have a custom del and decref it in the `__exit__` call (which then explicitly, and correctly, manages the lifetime), having created the `internal_comm` in `__enter__`.

So something like:

```python
class temp_internal:
    def __init__(self, comm):
        self.user_comm = comm
    def __enter__(self):
         self.internal_comm = internal_comm(self.user_comm)
         return self.internal_comm
    def __exit__(self, ...):
        decref(self.internal_comm)
        del self.internal_comm # stop people using it.
```

**Comment by JDBetteridge** [comment]
I'll add it to the to do list!
