### ISSUE TITLE
Tests aren't passing with GCC 14

### ISSUE THREAD

**Issue by JDBetteridge** [OP2/PyOP2#725]
The PyOP2 test suite fails with my gcc which is version 14.1.1.

In many places CStringKernels fail to compile with errors like:
```
/tmp/pyop2-cache-uid1481007/c1/64d3feccd06d55b4a691f067660e65_p2451144.c:29:7: error: passing argument 1 of ‘k’ from incompatible pointer type [-Wincompatible-pointer-types]
   29 |     k(&(t0[0]));
      |       ^~~~~~~~
      |       |
      |       int32_t * {aka int *}
/tmp/pyop2-cache-uid1481007/c1/64d3feccd06d55b4a691f067660e65_p2451144.c:5:27: note: expected ‘int (*)[2]’ but argument is of type ‘int32_t *’ {aka ‘int *’}
    5 |         static void k(int vd[1][2]) {
      |                       ~~~~^~~~~~~~
```

I think the correct thing to do is go through the test suite and update all of the incompatible CStringKernels (~18 failing tests). I don't think there is a nicer way of handling this issue.

**Comment by connorjward** [comment]
closing as replaced by https://github.com/firedrakeproject/firedrake/issues/3818
