### ISSUE TITLE
Add support for Intel OneAPI compilers

### ISSUE THREAD

**Issue by dsroberts** [OP2/PyOP2#728]
PyOP2 can't autodetect the Intel OneAPI compilers. Adding detection in the `sniff_compiler()` function would be pretty straightforward, output from `icx --version` looks like this:
```
Intel(R) oneAPI DPC++/C++ Compiler 2024.2.0 (2024.2.0.20240602)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /apps/intel-tools/.packages/2024.2.0/compiler/2024.2/bin/compiler
Configuration file: /apps/intel-tools/.packages/2024.2.0/compiler/2024.2/bin/compiler/../icx.cfg
```
The OneAPI compilers may have to be considered separately to the classic Intel compilers as the `-no-multibyte-chars` option has been removed with no replacement (as far as I can tell) and some LLVM flags are supported (e.g. `-ffast-math`).

**Comment by connorjward** [comment]
Moved to Firedrake: https://github.com/firedrakeproject/firedrake/issues/3819
